### ISSUE TITLE
Ability to click through individual timeframes, e.g. with keyboard

### ISSUE THREAD

**Issue by cmosig** [msoechting/lexcube#5]
**Describe the solution you'd like**

I use the viz a lot for debugging my data. It would often be nice to be able to tap through each timestep manually. Dragging with the mouse is imprecise and much slower.

This could either be a button or some key on the keyboard.

**Comment by msoechting** [comment]
Hi @cmosig! On my machine (Windows, Firefox), it is possible to control the sliders from `w.show_sliders()` using my keyboard. I click on any of the slider ends once and then can press the left and right arrow keys to control the clicked slider end. Let me know if this works also on your machine - maybe this is browser- or OS-dependent.

**Comment by cmosig** [comment]
Ah, I have not tried using the slider, thanks!
